Makefile

Remove GOARCH to support multi-arch build. We have an issue that compiled binary can't be executed on AL2 ARM.
````
2019-02-27T20:51:39Z [INFO] Restored cluster 'default'
2019-02-27T20:51:39Z [CRITICAL] Unable to initialize Task ENI dependencies: ecscni: failed invoking capabilities command for 'aws-appmesh': fork/exec /amazon-ecs-cni-plugins/aws-appmesh: exec format error
````

Remove GOARCH to support multi-arch build

---

plugins/aws-appmesh/config/netconfig.go
plugins/aws-appmesh/config/netconfig_test.go

Confirmed that iptables uid-owner/gid-owner can take both userid/groupid and numeric UID/GID. So remove the validation for IgnoredUID/IgnoredGID.

Remove IgnoredUID/IgnoredGID validation in aws-appmesh

---

plugins/vpc-branch-eni/config/netconfig.go
plugins/vpc-branch-eni/config/netconfig_test.go
plugins/vpc-branch-eni/plugin/commands.go

Use gateway ip address if specified in netconfig for vpc-branch-eni. Previously the branchGatewayIPAddress field in NetConfig of vpc-branch-eni can be provided but was never used, and the gateway ip was always inferred from the subnet. Existing behavior of ecs task networking is to supply the gateway ip address to ecs-eni plugin with the value specified in acs payload, and that will be the gateway ip to use. To use vpc-branch-eni plugin in eni trunking, we need to maintain the same behavior. This PR makes the necessary changes for that in the plugin.
Manually tested this by specifying a non-default gateway ip "172.31.16.2" in branchGatewayIPAddress field, and verified that the gateway ip is used in container's network namespace:
``` …
```

vpc-branch-eni plugin: use gateway ip address if specified in netconfig

---

Makefile

We added GOARCH as a environment variable to build amazon-vpc-cni-plugins [here](https://github.com/aws/amazon-ecs-agent/pull/1920/files#diff-68e77808f782cc71763dc5288e863117R19) as part of [this pr](https://github.com/aws/amazon-ecs-agent/pull/1920). 

Add GOARCH to aws-appmesh build tag

---

plugins/vpc-shared-eni/config/kubernetes.go

*Issue #, if available:* N/A
Use annotations instead of labels to assign IP address for pods. 
*Testing:*
Manually updated the plugin on the instance to validate the changes. 
Signed-off-by: Vinothkumar Siddharth <sidvin@amazon.com>

vpc-shared-eni: Use annotations instead of labels

---

Makefile
plugins/aws-appmesh/e2eTests/e2e_test.go
plugins/vpc-branch-eni/e2eTests/e2e_test.go

Add e2e tests for vlan code path for vpc-branch-eni plugin.
make branch-e2e-tests

Add e2e tests for vlan code path for vpc-branch-eni plugin

---

network/eni/eni.go
network/eni/eni_test.go

During setting up a branch interface, the branch can have the same mac address as the trunk for a short period of time, and we may end up picking the branch's name when trying to get the trunk name by mac. Fixing it by picking the shortest name available since branch name is strictly longer than trunk.
Unit test added and passed. The e2e tests via vpc-branch-eni-e2e-tests target passed. Manual test in progress.

Fix a race condition in getting the trunk name via its mac

---

plugins/vpc-shared-eni/config/netconfig.go

Vpc-shared-eni plugin should validate the interface type specified in the netconfig file on Linux. The parameter is not applicable to Windows.

Validate interface type in vpc-shared-eni on Linux

---

Makefile

Adding a variable to enable customized build flags. Enables quicks builds during development without having to build the world.

Add variable for custom build flags

---

Makefile
plugins/vpc-shared-eni/network/bridge_linux.go

This PR consists of two independent commits for vpc-shared-eni Linux plugin:
1) Add capability to configure a neighbor entry for gateway IP address in pod network namespace. This will be used by L3 networking solution in a future PR.
2) Add a dummy interface to bridge to stabilize its MAC address. Comments in the code explain why this is necessary. Also making deleteBridge failure path best-effort by continuing on "does not exist" errors.

Improvements for vpc-shared-eni plugin on Linux

---

plugins/vpc-branch-eni/e2eTests/e2e_test.go
plugins/vpc-branch-eni/plugin/commands.go

We are previously assuming that trunk interface is always up, and for eni trunking, we implicitly rely on ec2-net-utils to bring it up. This PR removes that assumption.
Modified the existing e2e test to test the case where the trunk is not up at the beginning. Test passed with the fix, failed without the fix.
Built the plugin in to agent and manually tested the following scenarios:
1. Without the fix:
* ECS optimized AMI with default configuration: awsvpc task successfully started
* ECS optimized AMI with ec2-net-utils uninstalled (before agent start): awsvpc task failed to start
* Ubuntu AMI (which doesn't have ec2-net-utils): awsvpc task failed to start
* Ubuntu AMI (manually bring up trunk interface after agent start): awsvpc task …

vpc-branch-eni: bring up trunk interface before configuring branch

---

plugins/vpc-shared-eni/config/kubernetes.go
plugins/vpc-shared-eni/config/netconfig.go
plugins/vpc-shared-eni/network/bridge_linux.go
plugins/vpc-shared-eni/network/network.go
plugins/vpc-shared-eni/plugin/commands.go

This change implements:
1) vpc-shared-eni L3 mode for Linux, where the container network namespaces are connected to a bridge, and the traffic between the host ENI and the bridge is achieved by IP routing.
2) vpc-shared-eni CIDR mode support where the container IP addresses can be from any CIDR range, not necessarily from one of the host ENI's subnets.
3) As a consequence of (2), the plugin can no longer know whether the container IP address is from the same subnet as the ENI. Therefore it can't append the prefix length to the IP address in Kubernetes-specific config path. The input IP address must be in CIDR format.

vpc-shared-eni: Implement L3 mode and CIDR block support on Linux

---

network/ipcfg/ip.go
plugins/vpc-shared-eni/network/bridge_linux.go

vpc-shared-eni's L3 mode requires IP forwarding and ARP proxy to be enabled on Linux. We were previously configuring these outside the CNI plugin. To make the plugin more robust, without relying on any external configuration, the plugin now enables forwarding and ARP proxy on its interfaces.

vpc-shared-eni: Enable IP forwarding and ARP proxy when using L3 mode

---

network/vpc/vpc.go
plugins/vpc-shared-eni/network/bridge_linux.go

The Linux bridge picks the smallest MTU of the links attached to its port as its own MTU. The dummy link in vpc-shared-eni is being created without any MTUs, defaulting to 1500. The bridge then inherits this MTU of 1500 bytes because it is smaller than the MTU=9000 of other veth pairs connected to it.
This change:
1) Sets the dummy links MTU to 9001.
2) Changes the jumbo MTU from 9000 to 9001 to be consistent with VPC DHCP servers.

vpc-shared-eni: Set dummy link MTU for bridge to inherit

---

Makefile
tools/netnsexec/main.go

* Redirect child cmd process stdout/stderr to netnsexec stdout/stderr.
* Add versioning support and --version cmd option.

netnsexec: Redirect cmd stdout/stderr

---

go.sum
plugins/vpc-branch-eni/config/netconfig.go
plugins/vpc-branch-eni/config/netconfig_test.go
plugins/vpc-branch-eni/plugin/commands.go

* Adds multi-queue TAP interface support to vpc-branch-eni plugin: The plugin still defaults to single-queue. The number of queues is hardcoded for now, isn't exposed via netconfig yet. We can add that once we add the capability to firecracker-containerd.
* Move TAP interface properties to its own structure: Given that UID, GID and NumQueues are properties specific to TAP interfaces, it made sense to make it a sub-struct.
* Add branch gateway to per-container args: Not related to TAP interfaces. Just noticed that it was missing, added it as a separate commit.
* Add unit tests for netconfig validation: Unit tests for increasing validation coverage.
By submitting this pull request, I confirm that my contribution is made under the terms of …

Add multi-queue TAP interface support

---

network/eni/api.go
network/eni/branch.go
network/eni/eni_linux.go
plugins/vpc-branch-eni/plugin/commands.go

Before this change, changing a branch interface's type from VLAN to TAP required first calling CNI DEL to delete the VLAN interface, and then calling CNI ADD again to create the TAP interface. This meant links, bridges, etc. had to be deleted and recreated for no reason.
After this change, there is no need to call CNI DEL. ADD command now can convert an existing VLAN interface to a TAP interface. This simplifies the orchestrator agent code as well because it doesn't need to know the differences between stages.

vpc-branch-eni: Make ADDs idempotent when switching from VLAN to TAP

---

plugins/aws-appmesh/config/netconfig.go
plugins/aws-appmesh/config/netconfig_test.go
plugins/aws-appmesh/e2eTests/e2e_test.go
plugins/aws-appmesh/e2eTests/testdata/invalid_without_app_ports.json
plugins/aws-appmesh/e2eTests/testdata/invalid_without_proxy_egress_port.json
plugins/aws-appmesh/e2eTests/testdata/invalid_without_proxy_ingress_port.json
plugins/aws-appmesh/e2eTests/testdata/valid_ingress_egress.json
plugins/aws-appmesh/e2eTests/testdata/valid_without_ingress.json
plugins/aws-appmesh/plugin/commands.go

This is a cherry-pick of @kiranmeduri 's prior PR (#12) with incorporation of conflicting changes and minor updates on comment style.
*Testing:*
`make build e2e-test` only -- Do we have a documented way to test this in a real runtime environment?

aws-appmesh: Allow app ports to be optional

---

plugins/vpc-shared-eni/config/kubernetes.go
plugins/vpc-shared-eni/config/netconfig.go
plugins/vpc-shared-eni/plugin/commands.go

*Issue #42:*
- Containers and HNS Endpoints are being leaked when the pod object is already deleted from etcd and we are trying to get it using kube client in the delete request which results in the delete request to fail.  
We don't need to query the API Server on DEL command as we get the Endpoint details using the container ID. We only query the API Server on ADD command to get the IP Address from the Pod's Annotation.
Resolves: #42 

vpc-shared-eni: Remove call to get Pod from API Server in DEL command

---

plugins/vpc-shared-eni/config/kubernetes.go
plugins/vpc-shared-eni/config/netconfig.go
plugins/vpc-shared-eni/plugin/commands.go

Reverts aws/amazon-vpc-cni-plugins#44
Will do a follow up PR with the following 
- Pass the flag to config.New if it's a delete request and if true don't parse k8s Arguments and make K8s API Call.

Revert "vpc-shared-eni: Remove call to get Pod from API Server in DEL command"

---

plugins/vpc-shared-eni/network/bridge_windows.go

In DEL Command, when the HotDetachEndpoint API fails if the container no longer exists, we simply return the error which would lead to a leaked HNSEndpoint. Fixing it by logging the error and trying to delete the HNSEndpoint before returning the error.
*Testing*
Reproduced the scenario and from the logs below we can see that endpoint 5416E24E-09B6-4D47-B536-2B650919D8E9 is cleaned up in case we encounter an error of type ```ErrComputeSystemDoesNotExist``` on calling the ```HotDetachEndpoint```.
```
2020-08-10T07:41:36Z [ERROR] failed to detach endpoint 5416E24E-09B6-4D47-B536-2B650919D8E9 from container e86c2ef847de726870492686bc418f81fa17951e29a886dc8212676774e44a9f as it's no longer running: A virtual machine or container with the specified identifier does not …
```

vpc-shared-eni: Delete HNS Endpoint if HotDetachEndpoint fails

---

Makefile
plugins/vpc-eni/config/netconfig.go
plugins/vpc-eni/main.go
plugins/vpc-eni/network/network.go
plugins/vpc-eni/network/network_linux.go
plugins/vpc-eni/network/network_windows.go
plugins/vpc-eni/plugin/commands.go
plugins/vpc-eni/plugin/plugin.go
plugins/vpc-eni/vpc-eni.conf

**Description of changes:**
`'vpc-eni' plugin` has been added for enabling task(container) networking on Windows instances.
The plugin supports networking setup using HNS V1 as well as HNS V2 API's on Windows.
This plugin can support multiple features for AWS ECS Windows namely-
1. Task networking on Windows for EC2 launch type
2. Task networking on Windows for Fargate launch type
3. Setting up Task IAM roles/Task metadata on Windows for EC2 launch type
4. Setting up Task IAM roles/Task metadata on Windows for Fargate launch type
**Testing**
The plugin was tested manually for different configurations.
The scenario's which were tested are available [here](https://quip-amazon.com/0LTzAFemSaHd/CNI-Plugin-Test-scenarios).
By submitting this pull request, I confirm that my contribution is made …

Adding 'vpc-eni' plugin for task(container) networking on Windows

---

plugins/vpc-eni/network/network_windows.go

For Windows Server 2004 and Windows Server 20H2, `netsh interface` context omits the virtual interfaces created by HNS. Therefore, to make the plugin generic across all the Windows version, we are switching to Powershell command.

Changed the command to disable management vNIC

---

network/ipcfg/ip.go
network/vpc/address.go
plugins/vpc-shared-eni/config/kubeapi.go
plugins/vpc-shared-eni/config/kubernetes.go
plugins/vpc-shared-eni/config/netconfig.go
plugins/vpc-shared-eni/network/bridge_linux.go
plugins/vpc-shared-eni/network/bridge_windows.go
plugins/vpc-shared-eni/network/network.go
plugins/vpc-shared-eni/plugin/commands.go
plugins/vpc-shared-eni/vpc-shared-eni.conf

vpc shared eni does not support v6 addresses currently.
Adding support within vpc shared eni to assign v6 address to eth0 interface in the pod network namespace.

Adding ipv6 support for vpc shared eni

---

plugins/vpc-branch-pat-eni/config/netconfig.go

In the vpc-branch-pat-eni plugin, an optional branch IP address is parsed. In order to accomplish this, ipAddr is dereferenced. While err is checked against nil, the check is after ipAddr is dereferenced, which may result in a nil pointer dereference panic.

vpc-branch-pat-eni: properly check for nil

---

Makefile

This prevents "go test" from messing with the packages under vendor directory.

Enumerate go packages to be tested explicitly

---

plugins/vpc-shared-eni/config/kubeapi.go

We are changing Kubernetes build flag from opt-out to opt-in, so that by
default plain CNI plugin builds won't have to build Kubernetes packages.

Fix vpc-shared-eni build flag for Kubernetes

---

plugins/vpc-branch-eni/plugin/commands.go
plugins/vpc-tunnel/plugin/commands.go

A specific error returned while deleting resources inside a network
namespace was not logged. Added the log to improve visibility.
*Description of changes:* The branch and tunnel plugins executes a function inside a network namespace as part of their DEL workflow. Sometimes we noticed there are chances that execution of that function inside the network namespace fail due to unknown reasons. A certain error in the workflow was noticed to be not logged. This change ensure that error is logged so that we will have better visibility.

Add missing logging in branch and tunnel plugins

---

Makefile

Remove the deprecated vpc-branch-pat-eni plugin from Makefile all-plugin target.

Remove the deprecated vpc-branch-pat-eni plugin from builds

---

plugins/aws-appmesh/config/netconfig.go
plugins/aws-appmesh/config/netconfig_test.go
plugins/aws-appmesh/plugin/commands.go

https://github.com/aws/aws-app-mesh-roadmap/issues/269
Ignore egress ports using multiple iptables rules. This is a workaround for iptables limit of 15 ports per rule. https://linux.die.net/man/8/iptables. Some customers require ignoring more than 15 ports.

Multiple rules for ignoring egress ports

---

network/ipcfg/ip.go
plugins/vpc-shared-eni/network/bridge_linux.go

For issue https://github.com/aws/amazon-vpc-cni-plugins/issues/78
Setting the bridge proxy delay to 0. This is to prevent the ARP proxy delays EKS Fargate has seen in production.
Tested internally and saw that this removed the long ARP delay we were seeing previously.

Setting bridge proxy delay to 0

---

plugins/vpc-shared-eni/plugin/plugin.go

Added 0.4.0 to Supported CNI spec list for vpc-shared-eni plugin. k8s 1.24 requires 0.4.0 CNI Spec.
*Testing:*
I have tested this change in 1.24 Windows EKS AMIs. Sanity tests and functional tests passed with this change.  

Added 0.4.0 in supported CNI Spec version list

---

network/imds/imds_linux.go
network/vpc/vpc.go
plugins/vpc-branch-eni/e2eTests/e2e_test.go

When the CNI plugins in this repo were implemented, IMDS was accessible only over IPv4. EC2 networking team 
introduced IMDS access over IPv6 last year. This change extends the BlockIMDS functionality to cover IPV6.
*Testing:*
`make unit-test`

Block IMDS access over IPv6 when BlockIMDS is set

---

network/imds/imds_windows.go
network/vpc/vpc.go

This is a follow-up for https://github.com/aws/amazon-vpc-cni-plugins/pull/84. We introduced IMDS IPv6 endpoint in the previous PR, however for Windows we will keep blocking IPv4 endpoint only until we can block IPv6 endpoint using HNS.
Update Windows BlockIMDS to use IPv4 endpoint only
`GOOS=windows make vpc-eni ` and `GOOS=windows make vpc-shared-eni` both built successfully.

Update Windows BlockIMDS to use IPv4 endpoint only

---

.github/workflows/build.yaml
.github/workflows/e2e.yaml
CONTRIBUTING.md
README.md
TESTING.md
go.sum
plugins/aws-appmesh/e2eTests/e2e_test.go
plugins/ecs-serviceconnect/e2eTests/e2e_test.go
plugins/vpc-branch-eni/e2eTests/e2e_test.go
plugins/vpc-tunnel/e2eTests/e2e_test.go

- added a log collector workflow that will pull failed CNI plugin tests log and attach them as artifacts
- added a `TESTING.md` file that goes over some of the testing setup
- migrated `ioutil` to `os` calls
- changed all of the tests to have unique network namespaces
- updated vpc-tunnel test to pass the right arguments to exec
- added the right required setup (creating `eth1` and `eth2` dummy links) to the github workflow
- use a different set of inputs for the `TestAddDelBlockIMDS` test and the `TestAddDel` test
- added a template builder and fields map to make the vpc-branch-eni tests read a little better

Fix end to end tests and some other improvements

---

network/vpc/port.go
network/vpc/protocol.go
network/vpc/protocol_test.go
plugins/vpc-bridge/config/netconfig.go
plugins/vpc-bridge/network/bridge_windows.go
plugins/vpc-bridge/network/network.go
plugins/vpc-bridge/plugin/commands.go

`vpc-bridge` CNI plugin (previously known as `vpc-shared-eni`) is used for networking on Windows nodes running in EKS. Presently, we do not support container to host port mapping using this CNI plugin. Therefore, `vpc-bridge` plugin silently ignores any port mapping between container to host for the configured endpoint.
As per the CNI convention, plugins can request that the runtime insert this dynamic configuration by explicitly listing their capabilities in the network configuration. Dynamic information (i.e. data that a runtime fills out) should be placed in a runtimeConfig section. 
Reference: https://www.cni.dev/docs/conventions/#dynamic-plugin-specific-fields-capabilities--runtime-configuration
`portMappings` is one such capability.
In order to support host port usage, we need to …

[vpc-bridge] Support host port mapping for Windows

---

plugins/vpc-bridge/network/bridge_windows.go

This is a bug fix in the `vpc-bridge` CNI plugin for Windows where we need to use `Search` parameter in `DNS` configuration for setting multiple domains used for short hostname lookups. Earlier we were using `Domain` which is a single string.
This change fixes this issue.
---

windows: use Search instead of Domain for DNS settings

---

plugins/vpc-bridge/README.md
plugins/vpc-bridge/config/k8s/connector.go

Lower privilege user on Windows can change path to binary in `AWS_VPC_CNI_K8S_CONNECTOR_BINARY_PATH` env variable to execute unintended binary with highest privilege.
Removing env variable AWS_VPC_CNI_K8S_CONNECTOR_BINARY_PATH which was used by CNI to get path to connector binary. CNI plugin will use hard-coded path to binary and execute it i.e. `C:\Program Files\Amazon\EKS\bin\aws-vpc-cni-k8s-connector.exe`

vpc-bridge plugin use hard-coded path to k8s connector binary

---

network/eni/eni_linux.go
plugins/vpc-eni/config/netconfig.go
plugins/vpc-eni/network/network.go
plugins/vpc-eni/network/network_linux.go
plugins/vpc-eni/plugin/commands.go
plugins/vpc-eni/vpc-eni.conf

We currently maintain two ENI (Elastic Network Interface) plugins: ecs-eni in the amazon-ecs-cni-plugins repository, and vpc-eni in this repository. The former is for Linux whereas the latter is for Windows. Functionally they implement the exact same behavior used for VPC networking (a.k.a. awsvpc mode) in ECS.
This change merges the two plugins into one (vpc-eni) to eliminate parallel development and simplify deployments.

Consolidate ecs-eni plugin into vpc-eni plugin

---

.github/workflows/e2e.yaml
plugins/vpc-eni/e2eTests/e2e_test.go
plugins/vpc-tunnel/e2eTests/e2e_test.go

This PR makes the following two changes.
e2e tests are flaky because vpc-tunnel plugin's tests and vpc-branch-eni plugin's tests both use `eth2` test interface causing conflicts. This PR fixes this flakiness by creating a new `eth3` test interface and by making vpc-tunnel plugin use `eth3` test interface. 
vpc-eni plugin tests (and other e2e tests) assume that test interfaces are already set up. This PR replaces this assumption in the tests by adding dynamic test interface creation and cleanup capability. This is better as the test runner (either human or CI) no longer needs to maintain the test interfaces for vpc-eni tests.

Deflake integration tests and dynamically create test interface for vpc-eni tests
